#!/usr/bin/env python3
# -*- encoding: utf-8 -*-
'''
First, install the latest release of Python wrapper: $ pip install ovh
'''
import sys
import os.path
import shutil
import ovh
import yaml

config_file = '~/.config/ovh-redirections.yaml'
domain_db_suffix = '_ovh-redirections.yaml'

def help():
    print('Usage: {} <command>\n\nCommands:'.format(sys.argv[0]))
    for f in sorted(globals().keys()):
        if not f.startswith('_') and callable(globals()[f]):
            print('    {}'.format(f))
    sys.exit(1)

try:
    f_config = open(os.path.expanduser(config_file), 'r')
except:
    print('No config file found {}\n'.format(config_file))
    config = { 'example.com': { 'endpoint': 'ovh-eu', 'application_key': 'YourApplicationKey', 'application_secret': 'YourApplicationSecret', 'consumer_key': 'YourConsumerKey' } }
    print('Configuration sample:\n')
    print(yaml.dump(config, indent=4, default_flow_style=False))
    sys.exit(1)

configs = yaml.load(f_config)

if len(configs.keys()) == 1:
    domain = list(configs.keys())[0]
    print('Using "{}" domain configuration…'.format(domain))
    config = configs[domain]
    client = ovh.Client(
        endpoint=config['endpoint'],
        application_key=config['application_key'],
        application_secret=config['application_secret'],
        consumer_key=config['consumer_key'],
    )
else:
    print('Multi-domain support are not yet implemented…')
    sys.exit(1)
remote_db = '.{}{}'.format(domain, domain_db_suffix)
local_db = '{}{}'.format(domain, domain_db_suffix)
url_base = '/email/domain/{}/redirection'.format(domain)

def _group_redirections(redirections):
    # Build a dict
    redirections_dict = {}
    for r in redirections:
        r_from = r['from']
        if r_from not in redirections_dict:
            redirections_dict[r_from] = []
        r.pop('from')
        redirections_dict[r_from].append(r)
    return redirections_dict

def fetch():
    redirections_id_list = client.get(url_base)
    print('{} redirections found, fetching details…'.format(len(redirections_id_list)))
    redirections = []
    for r_id in redirections_id_list:
        redirection = client.get(url_base + '/{}'.format(r_id))
        redirections.append(redirection)

    redirections_dict = _group_redirections(redirections)
    f_r = open(remote_db, 'w')
    yaml.dump(redirections_dict, f_r, indent=2, default_flow_style=False)
    print('Redirections written to "{}"'.format(remote_db))

def checkout():
    shutil.copyfile(remote_db, local_db)

def _open_local_db(flag='r'):
    try:
        f = open(local_db, flag)
    except Exception as e:
        print(str(e))
        print("Maybe you missed to run '{} checkout' before ?".format(sys.argv[0]))
        sys.exit(1)
    return f

def list():
    f = _open_local_db()
    r_redirections = yaml.load(f)
    _print_redirections(r_redirections)

def _print_redirections(redirections):
    # Print redirections (grouped)
    for r_from in sorted(redirections.keys()):
        if redirections[r_from]:
            print(r_from)
            for redirection in redirections[r_from]:
                print('  %s (%s)' % (redirection['to'], redirection['id']))
            print()

def _print_flat_redirections(redirections, fmt='{}'):
    for r in redirections:
        out = '{} -> {} ({})'.format(r[1], r[2], r[0])
        print(fmt.format(out))

def _flat_redirections(redirections):
    flat_redirections = []
    for r_from in sorted(redirections.keys()):
        if redirections[r_from]:
            for redirection in redirections[r_from]:
                r_id = redirection['id']
                #flat_redirections.append({ 'id': r_id, 'from': r_from, 'to': redirection['to']})
                flat_redirections.append( (r_id, r_from, redirection['to']) )
    return flat_redirections

def diff():
    f_l = _open_local_db()
    l_redirections = _flat_redirections(yaml.load(f_l))
    f_r = open(remote_db, 'r')
    r_redirections = _flat_redirections(yaml.load(f_r))

    removed = set(r_redirections) - set(l_redirections)
    added = set(l_redirections) - set(r_redirections)

    if(len(removed)):
        print('Removed:')
        _print_flat_redirections(removed, fmt='\t\033[91m{}\033[00m')
    else:
        print('Nothing to remove.')

    if(len(added)):
        print('Added:')
        _print_flat_redirections(added, fmt='\t\033[92m{}\033[00m')
    else:
        print('Nothing to add.')

if len(sys.argv) == 1:
    help()
else:
    if sys.argv[1] in locals():
        locals()[sys.argv[1]]()
    else:
        help()
